spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 10

  # testContainer 사용시 반드시 password를 설정해야 함
  # testContainer 사용시 redis test container에서 host와 port re-mapping이 필요함
  # RedisTestContainers.java 참조
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      password: password



decorator:
  datasource:
    p6spy:
      enable-logging: true
