server:
  port: 8080

spring:
  profiles:
    active: local
  mvc:
    # DispatcherServlet의 log 활성화 : logging.level.web = debug일 경우만
    log-request-details: true

  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10


logging:
  level:
    # DispatcherServlet의 log 활성화 : logging.level.web = debug일 경우만
    web: debug
    com.fastcampus: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true


