### 게시글 생성
POST localhost:8080/posts
Content-Type: application/json

{
    "title": "게시글",
    "content": "게시글 콘텐트",
    "createdBy": "me"
}


### 게시글 변경
PUT localhost:8080/posts/1
Content-Type: application/json

{
    "title": "게시글1",
    "content": "게시글 콘텐트11",
    "updatedBy": "me"
}

### 게시글 삭제
DELETE localhost:8080/posts/1?deletedBy="kkk"

### 게시글 상세
GET localhost:8080/posts/1

### 게시글 조회
GET localhost:8080/posts?page=1&size=10&title=&createdBy=user


